### ISSUE TITLE
Fatal error on PHP project.

### ISSUE THREAD

**Issue by sagormax** [Shipu/php-aamarpay-payment#3]
Is there any dependency on Laravel of this package? I am getting fatal error on raw php implementation.
![Screenshot from 2019-07-24 22-12-13](https://user-images.githubusercontent.com/11333602/61810205-8c924380-ae60-11e9-9aa8-3891b19234ed.png)

**Comment by Shipu** [comment]
use `dev-master` branch .

**Comment by Shipu** [comment]
Fixed in `v1.2.1`
